name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - env-*
      - enveu-*

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: set env
        run: echo "NOW=v.$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG:  ${{ github.ref_name }}-${{ env.NOW }}
      # (Optional) GitHub Enterprise requires GHE_HOST variable set
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Draft Release notes
        id: draft-release-notes
        uses: release-drafter/release-drafter@v5
        if: github.ref == 'refs/heads/env-prod'
        with:
          config-name: release-drafter.yml
          publish: false
          tag: ${{ steps.bump-version.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm install asana
      # execute the script file
      - name: Add asana task details and publish release notes
        uses: actions/github-script@v4
        id: add-asana-task-details
        if: github.ref == 'refs/heads/env-prod'
        with:
          script: |
            const script = require('.github/asana-link.js').replaceReleaseBodyAndPublish;
            return await script(github, context);
        env:
          ASANA_PAT: ${{ secrets.ASANA_PAT }}
          WORKSPACE_GID: '1185135203815182'
          RELEASE_ID: ${{ steps.draft-release-notes.outputs.id }}
          BODY: ${{ steps.draft-release-notes.outputs.body }}
